import type { IvrCampaign, CallRecord, LeadList, AgentGroup, DispositionRule, DidNumber } from './types';

export const INITIAL_CAMPAIGNS: IvrCampaign[] = [
  {
    id: 'camp-1',
    name: 'MASTER SMIT 7',
    subtitle: 'Concurrency 75',
    status: 'running',
    statusKind: 'running',
    state: 'active',
    concurrency: 75,
    progressPercentage: 7,
    dialedLeads: 37900,
    totalLeads: 505800,
    queued: 467900,
    dialing: 72,
    completed: 1516,
    interested: 97,
    metrics: {
      total: 505800,
      dialed: 37900,
      queued: 467900,
      dialing: 72,
      completed: 1516,
      interested: 97,
      concurrency: 75,
    },
    progress: 7,
    leadListName: 'US Financial Pre-Approved Leads Q1',
    audioPrompt: 'Rexera_Financial_PreApproval_Offer_v4.mp3',
    didPool: 'Direct Line Pool A (24 DIDs)',
    transferGroup: 'Executive Loan Officers',
    createdAt: '2026-03-28 09:30 AM',
    raw: {},
  },
  {
    id: 'camp-2',
    name: 'new master 6',
    subtitle: 'funding ivr leads h f n b',
    status: 'running',
    statusKind: 'running',
    state: 'active',
    concurrency: 75,
    progressPercentage: 52,
    dialedLeads: 111900,
    totalLeads: 213800,
    queued: 101900,
    dialing: 75,
    completed: 11700,
    interested: 260,
    metrics: {
      total: 213800,
      dialed: 111900,
      queued: 101900,
      dialing: 75,
      completed: 11700,
      interested: 260,
      concurrency: 75,
    },
    progress: 52,
    leadListName: 'SMB Funding Verified List March',
    audioPrompt: 'SMB_Working_Capital_Prompt_v2.wav',
    didPool: 'High Concurrency Trunk 1',
    transferGroup: 'Business Loan Specialists',
    createdAt: '2026-03-27 11:15 AM',
    raw: {},
  },
  {
    id: 'camp-3',
    name: 'master smit 3',
    subtitle: 'Concurrency 75',
    status: 'paused',
    statusKind: 'paused',
    state: 'active',
    concurrency: 75,
    progressPercentage: 99,
    dialedLeads: 466400,
    totalLeads: 472000,
    queued: 5571,
    dialing: 0,
    completed: 82000,
    interested: 1451,
    metrics: {
      total: 472000,
      dialed: 466400,
      queued: 5571,
      dialing: 0,
      completed: 82000,
      interested: 1451,
      concurrency: 75,
    },
    progress: 99,
    leadListName: 'Commercial Real Estate Leads',
    audioPrompt: 'Commercial_Property_Finance.mp3',
    didPool: 'Tier-1 Telecom Pool',
    transferGroup: 'Senior Underwriting Desk',
    createdAt: '2026-03-25 08:45 AM',
    raw: {},
  },
];

export const INITIAL_CALL_RECORDS: CallRecord[] = [
  {
    id: 'cdr-1092',
    leadPhone: '+1 (555) 382-9104',
    leadName: 'David Miller',
    callerId: '+1 (800) 482-1940',
    campaignId: 'camp-1',
    campaignName: 'MASTER SMIT 7',
    durationSeconds: 42,
    dtmfKey: '1',
    disposition: 'Interested',
    callTime: 'Just now',
    agentName: 'Sarah Jenkins',
    audioUrl: 'https://example.com/recording-1.mp3',
  },
  {
    id: 'cdr-1091',
    leadPhone: '+1 (555) 749-2810',
    leadName: 'Emma Watson',
    callerId: '+1 (800) 482-1941',
    campaignId: 'camp-1',
    campaignName: 'MASTER SMIT 7',
    durationSeconds: 28,
    dtmfKey: '1',
    disposition: 'Transferred',
    callTime: '2 mins ago',
    agentName: 'Michael Chang',
    audioUrl: 'https://example.com/recording-2.mp3',
  },
  {
    id: 'cdr-1090',
    leadPhone: '+1 (555) 902-3481',
    leadName: 'Robert Johnson',
    callerId: '+1 (800) 482-1940',
    campaignId: 'camp-2',
    campaignName: 'new master 6',
    durationSeconds: 15,
    dtmfKey: '9',
    disposition: 'DNC',
    callTime: '4 mins ago',
  },
  {
    id: 'cdr-1089',
    leadPhone: '+1 (555) 612-8839',
    leadName: 'Elena Rostova',
    callerId: '+1 (800) 482-1942',
    campaignId: 'camp-2',
    campaignName: 'new master 6',
    durationSeconds: 38,
    dtmfKey: '1',
    disposition: 'Interested',
    callTime: '7 mins ago',
    agentName: 'Jessica Taylor',
  },
  {
    id: 'cdr-1088',
    leadPhone: '+1 (555) 244-1920',
    leadName: 'James Harrison',
    callerId: '+1 (800) 482-1943',
    campaignId: 'camp-1',
    campaignName: 'MASTER SMIT 7',
    durationSeconds: 5,
    disposition: 'No Answer',
    callTime: '10 mins ago',
  },
  {
    id: 'cdr-1087',
    leadPhone: '+1 (555) 881-2093',
    leadName: 'Sophia Lee',
    callerId: '+1 (800) 482-1940',
    campaignId: 'camp-3',
    campaignName: 'master smit 3',
    durationSeconds: 56,
    dtmfKey: '1',
    disposition: 'Interested',
    callTime: '15 mins ago',
    agentName: 'Alex Morgan',
  },
];

export const INITIAL_LEAD_LISTS: LeadList[] = [
  {
    id: 'list-1',
    name: 'US Financial Pre-Approved Leads Q1',
    totalCount: 505800,
    validCount: 498200,
    dncFilteredCount: 7600,
    uploadedAt: '2026-03-28',
    status: 'In Use',
  },
  {
    id: 'list-2',
    name: 'SMB Funding Verified List March',
    totalCount: 213800,
    validCount: 209500,
    dncFilteredCount: 4300,
    uploadedAt: '2026-03-27',
    status: 'In Use',
  },
  {
    id: 'list-3',
    name: 'Commercial Real Estate Leads',
    totalCount: 472000,
    validCount: 465100,
    dncFilteredCount: 6900,
    uploadedAt: '2026-03-25',
    status: 'In Use',
  },
  {
    id: 'list-4',
    name: 'Mortgage Refinance Homeowners 2026',
    totalCount: 350000,
    validCount: 342000,
    dncFilteredCount: 8000,
    uploadedAt: '2026-03-29',
    status: 'Ready',
  },
];

export const INITIAL_AGENT_GROUPS: AgentGroup[] = [
  {
    id: 'grp-1',
    name: 'Executive Loan Officers',
    description: 'Priority queue for pre-approved high-ticket finance leads',
    activeAgents: 18,
    totalAgents: 24,
    transferDid: '+1 (800) 555-0199',
    liveCallsCount: 14,
  },
  {
    id: 'grp-2',
    name: 'Business Loan Specialists',
    description: 'Direct transfer team for SMB working capital requests',
    activeAgents: 12,
    totalAgents: 15,
    transferDid: '+1 (800) 555-0188',
    liveCallsCount: 9,
  },
  {
    id: 'grp-3',
    name: 'Senior Underwriting Desk',
    description: 'Commercial mortgage and high-volume deals',
    activeAgents: 8,
    totalAgents: 10,
    transferDid: '+1 (800) 555-0177',
    liveCallsCount: 5,
  },
];

export const INITIAL_DISPOSITIONS: DispositionRule[] = [
  { key: '1', label: 'Interested / Warm Lead', action: 'Transfer', targetGroup: 'Executive Loan Officers', smsFollowup: true },
  { key: '2', label: 'Call Back Later', action: 'Callback', smsFollowup: true },
  { key: '3', label: 'Not Interested', action: 'Hangup', smsFollowup: false },
  { key: '9', label: 'Do Not Call (DNC)', action: 'DNC', smsFollowup: false },
];

export const INITIAL_DIDS: DidNumber[] = [
  { id: 'did-1', number: '+1 (800) 482-1940', carrier: 'Bandwidth Tier 1', state: 'US Nationwide', assignedCampaign: 'MASTER SMIT 7', callsToday: 8420, spamScore: 'Low', status: 'Active' },
  { id: 'did-2', number: '+1 (800) 482-1941', carrier: 'Twilio Direct', state: 'US Nationwide', assignedCampaign: 'MASTER SMIT 7', callsToday: 8310, spamScore: 'Low', status: 'Active' },
  { id: 'did-3', number: '+1 (800) 482-1942', carrier: 'Telnyx Voice', state: 'US Nationwide', assignedCampaign: 'new master 6', callsToday: 6540, spamScore: 'Low', status: 'Active' },
  { id: 'did-4', number: '+1 (800) 482-1943', carrier: 'Telnyx Voice', state: 'US Nationwide', assignedCampaign: 'new master 6', callsToday: 6290, spamScore: 'Low', status: 'Active' },
  { id: 'did-5', number: '+1 (800) 482-1944', carrier: 'Bandwidth Tier 1', state: 'US Nationwide', assignedCampaign: 'master smit 3', callsToday: 120, spamScore: 'Low', status: 'Active' },
];
