"""SQL generated by the Postgres document adapter (no database needed)."""
import json

import pytest

from app.database import build_where, _json_ref


def where(flt):
    params, counter = {}, [0]
    return build_where(flt, params, counter), params


def test_equality_uses_containment():
    sql, params = where({"status": "Active"})
    assert sql == "data @> (:p0)::jsonb"
    assert json.loads(params["p0"]) == {"status": "Active"}


def test_dotted_key_matches_nested_document():
    sql, params = where({"client.name": "Acme"})
    assert json.loads(params["p0"]) == {"client": {"name": "Acme"}}
    sql, params = where({"client.name": {"$regex": "ac", "$options": "i"}})
    assert sql == "data#>>'{client,name}' ~* :p0"


def test_comparison_and_sort_refs():
    assert _json_ref("amount", as_text=False) == "data->'amount'"
    assert _json_ref("created_at", as_text=True) == "data->>'created_at'"
    assert _json_ref("a.b", as_text=True) == "data#>>'{a,b}'"


@pytest.mark.parametrize("key", ["x') DESC; DROP TABLE t; --", "a'b", "a b", "", "1abc", "a..b", "$where"])
def test_unsafe_keys_are_rejected(key):
    with pytest.raises(ValueError):
        where({key: 1})
    with pytest.raises(ValueError):
        _json_ref(key, as_text=True)


def test_unknown_operator_is_rejected():
    with pytest.raises(ValueError):
        where({"a": {"$where": "1=1"}})


def test_values_are_always_bound_parameters():
    sql, params = where({"$or": [{"name": {"$regex": "'; DROP"}}, {"_id": "x' OR '1'='1"}]})
    assert "DROP" not in sql and "'1'='1" not in sql
    assert "'; DROP" in params.values()
